data=read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors = FALSE)
library(dplyr)
two_day_data=filter(data,Date=="1/2/2007"|Date=="2/2/2007")
dt=paste(two_day_data$Date,two_day_data$Time,sep=" ")
two_day_data$DateTime=strptime(dt,format="%d/%m/%Y %H:%M:%S")
daterange=c(min(two_day_data$DateTime),max(two_day_data$DateTime))
png(filename = "plot2.png")
plot(two_day_data$DateTime,as.numeric(two_day_data$Global_active_power),type="l",xaxt="n",xlab="",ylab="Global Active Power (kilowatt)")
axis.POSIXct(1,seq(daterange[1],daterange[2],by="day"),format="%a")
dev.off()